### ISSUE TITLE
How to  Electrical Wiring

### ISSUE THREAD

**Issue by wanball** [petrepa/ESPHome-VideoDoorbell#7]
Sorry for my English.

From your picture. Your green and blue wires, what do they connect to?

I have plans to connect it to a relay. so I can use the old doorbell.

![image](https://github.com/petrepa/ESPHome-VideoDoorbell/assets/13687974/dc4301d0-7010-415a-bf3d-0c35a41b1bbb)

my doorbell
![image](https://github.com/petrepa/ESPHome-VideoDoorbell/assets/13687974/aa87456a-72f5-4255-a15e-e6ce4abcdb32)

**Comment by petrepa** [comment]
Since completing this project, I have relocated and no longer have the setup available to reference directly. However, you can find wiring and connection information in the README: [ESPHome-Doorbell - Connections](https://github.com/petrepa/ESPHome-VideoDoorbell?tab=readme-ov-file#connections).

Unfortunately, I don't recall the exact connections for the green and blue wires for my specific setup.

Most standard doorbells operate on low-voltage AC power, which is likely the case for your setup. This means you cannot connect it directly to the ESP32, which requires a 3.3V DC power supply.

**Comment by wanball** [comment]
from your idea I took it to design for the stepdown power supply and my trigger doorbell.

I just don't know. What are your green and blue wires?

Thank you for responding so quickly. @petrepa 

my pcb
![image](https://github.com/petrepa/ESPHome-VideoDoorbell/assets/13687974/9aa4c285-22e5-43ef-b5ab-a091e105a251)

**Comment by petrepa** [comment]
I don't think I used the green and blue wire. I probably just wired them up in case I was going to use them. I can see from some of my old photos that I wired these to the reset button, but I did not use them I think. 
![image](https://github.com/petrepa/ESPHome-VideoDoorbell/assets/30476405/128027d4-23af-48ae-bc0f-f1cb69b82bae)
